version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - db
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client:/app

  db:
    container_name: db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "db-volume:/data/db"

volumes:
  db-volume:
