version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client:/app

  test:
    container_name: client_test
    build:
      context: ./client
    stdin_open: true
    volumes:
      - ./client:/app
    environment:
      - CI=true
    command: npm test
