version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - db
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client:/app

  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: "mongodb://db:27017"

  db:
    container_name: db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "db-volume:/data/db"

  test:
    container_name: client_test
    build:
      context: ./client
    stdin_open: true
    volumes:
      - ./client:/app
    environment:
      - CI=true
    command: npm test

volumes:
  db-volume:
